# DS4B 201-P: MACHINE LEARNING WITH PYTHON ----
# Environment Setup ----

# 1. Create an empty conda env ----
#  - Using an environment.yml file with conda
#  - Important Terminal Commands:
#     conda env create -f environment.yml
#
# Conda Environment Setup Instructions ----
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
# 
#    conda env create -f 00_environment_setup/01_conda_environment_nbdev.yml
#    conda env update --file 00_environment_setup/01_conda_environment_nbdev.yml --prune
#    conda env export --name nbdev > envname.yml
#    conda env remove --name nbdev
#    conda env list



# 2. Activate the Environment
#  - Command Palette > Python Select Interpreter
#  - Select nbdev environment
#  - May need to refresh
# 
# 3. Trash Any Open Terminals (Open a New Terminal)
#   
# 4. Pip Install Requirements (Will take 10 minutes or so)
#   - pip install -r requirements.txt
#   - In the event of any errors: Relax requirements and rerun: 
#       pip install -r requirements.txt


name: nbdev
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pip
  - pip:
      # Core Data
      - jupyterlab
      - nbdev
      - jupyterlab-quarto